# docker-compose.yml
version: '3.8'

services:
  sparql-muse:
    build: .
    ports:
      - "8012:8000"
    container_name: sparqlmuse
    volumes:
      - ./app:/app
      - ./data:/app/data
      - ./cache:/root/.cache/huggingface
    environment:
      - "SPARQL_ENDPOINT"
      - "SECRET_KEY"
      - "ALGORITHM"
      - "MIN_AMOUNT"
      - "TRANSFORMER_MODEL"
      - "ENTITY_OLLAMA_URL"
      - "ENTITY_MODEL_NAME"
      - THRESHOLD
      - CANDIDATE_MAX
    networks:
      - default
      - traefik
networks:
  traefik:
    external: true

